name: Linting
on: pull_request
jobs:
  prettier:
    name: Linting with Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/hydrogen"
      - run: npm ci
      - run: npm run lint:prettier:check
  Eslint:
    name: Linting with ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/hydrogen"
      - run: npm ci
      - run: npm run lint:eslint:check
